interface TermsPageProps {
  onBack: () => void;
}

export function TermsPage({ onBack }: TermsPageProps) {
  return (
    <div className="h-screen overflow-y-auto bg-white text-gray-900">
      <header className="sticky top-0 bg-white border-b border-gray-200 px-4 py-3 flex items-center gap-4 z-10">
        <button
          type="button"
          onClick={onBack}
          className="text-sm text-gray-600 hover:text-gray-900 flex items-center gap-1 shrink-0"
        >
          ← Back
        </button>
        <h1 className="text-lg font-semibold text-gray-900 m-0">Terms of Service</h1>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8">
        {/* Draft notice */}
        <div className="mb-6 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-amber-900 text-sm">
          Draft pending legal review.
        </div>

        <p className="text-sm text-gray-500 mb-8">Last updated: April 28, 2026</p>

        <h1 className="text-2xl font-bold mb-6">Terms of Service</h1>

        <h2 className="text-lg font-semibold mt-8 mb-3">1. Acceptable Use</h2>
        <p className="mb-4 leading-relaxed">
          Backpack Map is a platform for discovering, sharing, and organising travel experiences. You
          may use the service only for lawful purposes and in accordance with these Terms. You agree
          not to use the service in any way that violates applicable local, national, or international
          laws or regulations.
        </p>

        <h2 className="text-lg font-semibold mt-8 mb-3">2. Account Responsibility</h2>
        <p className="mb-4 leading-relaxed">
          Each person may create and maintain one account. You are responsible for safeguarding your
          account credentials and for all activity that occurs under your account. You agree to
          provide accurate, truthful information when registering and to keep your account details up
          to date.
        </p>

        <h2 className="text-lg font-semibold mt-8 mb-3">3. Content Ownership</h2>
        <p className="mb-4 leading-relaxed">
          You retain full ownership of the pins, itineraries, and other content you create and post
          on Backpack Map. By submitting content, you grant Backpack Map a non-exclusive, worldwide,
          royalty-free licence to display, reproduce, and distribute your content within the
          application solely for the purpose of operating and improving the service. This licence
          ends when you delete the content or close your account.
        </p>

        <h2 className="text-lg font-semibold mt-8 mb-3">4. Termination</h2>
        <p className="mb-4 leading-relaxed">
          We may suspend or terminate your account at our discretion if you breach these Terms,
          engage in illegal activity, or leave your account inactive for a prolonged period without
          interaction. You may delete your account at any time from your profile settings.
        </p>

        <h2 className="text-lg font-semibold mt-8 mb-3">5. Disclaimers</h2>
        <p className="mb-4 leading-relaxed">
          The service is provided <strong>"as is"</strong> without warranty of any kind, express or
          implied. Itineraries generated by the service are produced by artificial intelligence and
          are <strong>suggestions only — they are not professional travel advice</strong>. You assume
          full responsibility for your own travel decisions, safety, and wellbeing. We do not
          guarantee that any place recommended by the service is still open, safe, accessible, or
          lawful to visit at the time of your travel.
        </p>

        <h2 className="text-lg font-semibold mt-8 mb-3">6. Limitation of Liability</h2>
        <p className="mb-4 leading-relaxed">
          To the maximum extent permitted by applicable law, Backpack Map's total liability to you
          for any claim arising out of or relating to these Terms or the service is limited to the
          amount you have paid for the service. As the service is currently provided free of charge,
          that amount is <strong>zero (€0)</strong>.
        </p>

        <h2 className="text-lg font-semibold mt-8 mb-3">7. Changes to These Terms</h2>
        <p className="mb-4 leading-relaxed">
          We may update these Terms at any time. When we do, we will revise the "Last updated" date
          at the top of this page and, where appropriate, notify you by email or in-app notice. Your
          continued use of the service after any change takes effect constitutes your acceptance of
          the revised Terms.
        </p>

        <h2 className="text-lg font-semibold mt-8 mb-3">8. Governing Law</h2>
        <p className="mb-4 leading-relaxed">
          These Terms are governed by the laws of Italy and applicable European Union consumer
          protection law. Any disputes shall be resolved in the courts of competent jurisdiction in
          Italy, without prejudice to any mandatory consumer-protection rights you may hold under the
          law of your country of residence.
        </p>
        {/* TODO: review governing law if/when the entity is incorporated in a different jurisdiction */}

        <hr className="my-8 border-gray-200" />
        <p className="text-sm text-gray-500">
          Questions about these Terms? Contact us through the app.
        </p>
      </main>
    </div>
  );
}
